# sets generator options.
generator:
  # sets generator features.
  features:
    enable:
      # Enables paths client generation
      - 'paths/client'
      - 'client/security/reentrant'
      # Enables validation of client requests
      - 'client/request/validation'
      # Enables stub Handler generation
      - 'ogen/unimplemented'
    disable:
      # Disables paths server generation
      - 'paths/server'
    disable_all: true
